### ISSUE TITLE
Index - What it does

### ISSUE THREAD

**Issue by antoon-r** [pgcodekeeper/pgcodekeeper.github.io#1]
https://github.com/pgcodekeeper/pgcodekeeper.github.io/blob/bc44df51b4f1d355ecba457151a1d8214fae5503/_src/app/index.html#L71

Monitores the changings in the DB and creates the selected objects migration scripts both in interactive and automatic mode.

change to 

"Helps find changes between databases and create migration scripts for selected objects."

**Comment by asaushkin** [comment]
Will be fixed

**Comment by asaushkin** [comment]
Fixed
