### ISSUE TITLE
Index - Features - Headers

### ISSUE THREAD

**Issue by antoon-r** [pgcodekeeper/pgcodekeeper.github.io#3]
https://github.com/pgcodekeeper/pgcodekeeper.github.io/blob/bc44df51b4f1d355ecba457151a1d8214fae5503/_src/app/index.html#L81

Change 

Product capability => Features

Shows the changes between different DBs => Show changes between databases

Generates the migration scripts => Generate migration scripts

Working with the versions control systems => Support work [through|with] VCS (version control system)

Working with the continuous integration systems => Non-interactive mode for continuous integration systems

**Comment by asaushkin** [comment]
Done
