### ISSUE TITLE
pgsqlblocks.[ru.]html Изменить кнопку и ссылки на скачивание pgSqlBlocks

### ISSUE THREAD

**Issue by antoon-r** [pgcodekeeper/pgcodekeeper.github.io#4]
https://github.com/pgcodekeeper/pgcodekeeper.github.io/blob/bc44df51b4f1d355ecba457151a1d8214fae5503/_src/app/pgsqlblocks.html#L54

1. Переименовать кнопку в "Download pgSqlBlocks" и сделать так чтобы она вела на страницу https://github.com/technology16/pgsqlblocks/releases/latest

2. Удалить ссылку "Download another version"

3. В разделе how to install ссылку на скачивание pgSqlBlocks так же заменить на https://github.com/technology16/pgsqlblocks/releases/latest

4. В разделе how to install обновить версию в команде `java -jar pgSqlBlocks-1.4.0-Linux-64.jar`

**Comment by antoon-r** [comment]
На странице pgsqlblocks-article.html так же заменить ссылку pgcodekeeper.ru/pgsqlblocks на https://github.com/technology16/pgsqlblocks/releases/latest

**Comment by antoon-r** [comment]
@asaushkin @vasekdemakov  Надо бы еще ссылку pgcodekeeper.ru/pgsqlblocks смапить на pgcodekeeper.ru/pgsqlblocks/html, а там 404 от гитхаба.

**Comment by asaushkin** [comment]
А где pgcodekeeper.ru/pgsqlblocks/html используется?

**Comment by antoon-r** [comment]
Имел в виду хтмл страницу pgcodekeeper.ru/pgsqlblocks.html

**Comment by antoon-r** [comment]
Ссылка pgcodekeeper.ru/pgsqlblocks работает, не работает ссылка со слэшем в конце: pgcodekeeper.ru/pgsqlblocks/

@asaushkin предложил дополнительно копировать pgsqlblocks.html в файл ~/pgsqlblocks/index.html
