### ISSUE TITLE
Необходимо добавить cli версии для загрузки

### ISSUE THREAD

**Issue by asaushkin** [pgcodekeeper/pgcodekeeper.github.io#5]
И исправить ссылку за загрузку для пользователей

https://github.com/pgcodekeeper/pgcodekeeper.github.io/blob/6b92beb26f35b44a40d0d3b245a3a8ca2739e2ef/_src/app/index.html#L152

**Comment by Endeavourl** [comment]
Релиз временно прикреплен к этому репозиторию, ссылка изменена.
Коммит 3565249
